create table BATTING_DETAIL (
    ID integer generated by default as identity,
    TEAM_ID integer not null,
    PITCHER_ID integer not null,
    MISS_FLAG integer not null,
    PH_FLAG integer not null,
    MYTEAM_ID integer not null,
    GAME_ID integer not null,
    RESULT integer,
    PLAYER_ID integer not null,
    constraint BATTING_DETAIL_PK primary key(ID)
);
