create table BATTING_SUM (
    ID integer generated by default as identity,
    TEAM_ID integer not null,
    MYTEAM_ID integer not null,
    HOMERUN integer not null,
    TWOBASE integer not null,
    STRIKE_OUT integer not null,
    FOUR_BALL integer not null,
    RBI integer not null,
    HIT integer not null,
    AT_BATS integer not null,
    TPA integer not null,
    GAME_ID integer not null,
    PLAYER_ID integer not null,
    constraint BATTING_SUM_PK primary key(ID)
);
