create table LEAGUE (
    ID integer generated by default as identity,
    TOTAL_FLG integer not null,
    END_DATE date not null,
    BEGIN_DATE date not null,
    TITLE varchar(100) not null,
    constraint LEAGUE_PK primary key(ID)
);
